#ifndef APGC_H
#define APGC_H
typedef struct
{
    int count;
    char word[16][256];
} LineRead;
LineRead read_line(const char* line);
int is_const(const char* word);
short int read_const(const char* word);
enum CMD
{
    CMD_NONE = 0,
    DTC,
    CTD,
    ATP,
    MOV_NUM,
    MOV_VAR,
    ADD_NUM,
    ADD_VAR,
    SUB_NUM,
    SUB_VAR,
    MUL_NUM,
    MUL_VAR,
    DIV_NUM,
    DIV_VAR,
    MOD_NUM,
    MOD_VAR,
    SHL_NUM,
    SHL_VAR,
    SHR_NUM,
    SHR_VAR,
    AND_NUM,
    AND_VAR,
    OR_NUM,
    OR_VAR,
    XOR_NUM,
    XOR_VAR,
    CMP_NUM,
    CMP_VAR,
    NOT,
    SELF_INC,
    SELF_DEC,
    JMP,
    JE,
    JNE,
    JG,
    JGE,
    JL,
    JLE,
    CALL,
    RET
};
enum FUN
{
    FUN_NONE = 0,
    BTN_PRESS,
    FILL_SCR,
    SET_COLOR,
    DRAW_PIXEL,
    DRAW_LINE,
    DRAW_RECT,
    DRAW_CIRCLE,
    FILL_RECT,
    FILL_CIRCLE,
    DELAY,
    SHOW_ASCII,
    SHOW_ENGLISH,
    SHOW_HZ,
    SHOW_CHINESE,
    OPEN_MAP,
    MAP_SEEK,
    MAP_POSITION,
    MAP_READ,
    MAP_SIZE,
    CLOSE_MAP,
    GET_MAP_AMOUNT,
    GET_MAP_FLAG,
    SET_MAP_FLAG,
    NUM_PRINTF,
    SET_STRING,
    STR_CPY,
    STR_CAT,
    STR_CMP,
    STR_LEN,
    UPDATE_SAVE,
    UPDATE_MAP,
    EXIT_GAME
};
enum VAR
{
    VAR_NONE = 0,
    VAR_PIN,
    VAR_PRESSED,
    VAR_COLOR_R,
    VAR_COLOR_G,
    VAR_COLOR_B,
    VAR_POINT_X1,
    VAR_POINT_Y1,
    VAR_POINT_X2,
    VAR_POINT_Y2,
    VAR_RADIUS,
    VAR_TIME_DELAY,
    VAR_ASCII,
    VAR_ENGLISH,
    VAR_HZ,
    VAR_CHINESE,
    VAR_DOT,
    VAR_MAP_INDEX,
    VAR_MAP_OFFSET,
    VAR_MAP_POSITION,
    VAR_MAP_READ,
    VAR_MAP_SIZE,
    VAR_MAP_AMOUNT,
    VAR_MAP_X,
    VAR_MAP_Y,
    VAR_MAP_XY_FLAG,
    VAR_NUM,
    VAR_STR1,
    VAR_STR2,
    VAR_STR_CMP,
    VAR_STR_LEN,
    VAR_ALL,
    VAR_WIN,
    VAR_LOSE,
    VAR_INDEX1,
    VAR_INDEX2,
    VAR_UNSIGNED_CHAR,
    VAR_INT,
    VAR_STRING
};
#endif
